language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI 서버 home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

# Travis CI build -> S3 -> CodeDeploy
before_deploy:
  - zip -r mucketList_server *
  - mkdir -p deploy
  - mv mucketList_server.zip deploy/mucketList_server.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: mucketlist-server-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: dcide6/mucketList_server
      branch: master

# 메일 알람
notifications:
  email:
    recipients:
      - dcide6@gmail.com