spring:
  profiles:
    group:
      "local": "local, real-db"
      "set1": "set1, real-db"
      "set2": "set2, real-db"
  jpa:
    properties:
      hibernate.default_batch_fetch_size: 1000
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  file:
    path: "/home/ec2-user/app/logs"

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
cloud:
  aws:
    s3:
      bucket: mucketlist-server-image
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
       instanceProfile: true
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
---
#Local
spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080

  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

#운영
---
spring:
  config:
    activate:
      on-profile: set1

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: set2

server:
  port: 8082
