spring:
  profiles:
    group:
      "local": "local, real-db"
      "set1": "set1, real-db"
      "set2": "set2, real-db"
logging:
  file:
    path: "~/app/logs"

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
---
#Local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

#운영
---
spring:
  config:
    activate:
      on-profile: set1

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: set2

server:
  port: 8082
