spring:
  profiles:
    active: local #기본환경

#Test
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#test를 위한 임시 키 실제 운영시 ec2에 둘것.
jwt:
  base64-secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNpa3NhdXJ1cy1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3Qtc2lrc2F1cnVzCg==


#운영
---
spring:
  config:
    activate:
      on-profile: set1
    profiles:
      include: real-db

server:
  port: 8081

jwt:
  base64-secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNpa3NhdXJ1cy1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3Qtc2lrc2F1cnVzCg==

---
spring:
  config:
    activate:
      on-profile: set2
    profiles:
      include: real-db

server:
  port: 8082

jwt:
  base64-secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNpa3NhdXJ1cy1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3Qtc2lrc2F1cnVzCg==
