spring:
  profiles:
    active: local #기본환경
#Test
---
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  config:
    activate:
      on-profile: local

#운영
---
spring:
  config:
    activate:
      on-profile: set1
    profiles:
      include: real-db

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: set2
    profiles:
      include: real-db

server:
  port: 8082
